from flask import Flask, jsonify
from flask_cors import CORS
import pandas as pd
import os

app = Flask(__name__)
# Enable CORS so our Next.js frontend (running on port 3000) can make requests here
CORS(app)

@app.route('/api/predict', methods=['GET'])
def get_predictions():
    # The file path to the predictions generated by step4_predict_2026.py
    csv_path = os.path.join("csv", "2026_overflow_predictions.csv")
    
    # If the file doesn't exist yet, return an error
    if not os.path.exists(csv_path):
        return jsonify({"error": "Prediction file not found. Please run step4_predict_2026.py first!"}), 404
        
    try:
        # Read the CSV
        df = pd.read_csv(csv_path)
        
        # Month mapping for displaying friendly names in Next.js
        month_names = {
            1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun', 
            7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'
        }
        
        results = []
        
        # We need to aggregate the daily predictions into a monthly format for the frontend chart
        for month_num in range(1, 13):
            # Get all days for this month
            month_df = df[df['Month'] == month_num]
            
            if len(month_df) == 0:
                continue
                
            total_days = len(month_df)
            
            # Sum up how many days were predicted to have an overflow (Overflow_Prediction == 1)
            risk_days = int(month_df['Overflow_Prediction'].sum())
            safe_days = total_days - risk_days
            
            # Average probability across the month
            avg_prob = month_df['Overflow_Probability_%'].mean()
            
            results.append({
                "month": month_names[month_num],
                "total_days": total_days,
                "safe_days": safe_days,
                "risk_days": risk_days,
                "probability_percent": round(avg_prob, 2)
            })
            
        return jsonify(results)

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    print("=========================================================")
    print("    HydroSync ML Engine API is RUNNING on port 5000!")
    print("=========================================================")
    print("You can now refresh your Next.js Predictions page.")
    app.run(host='0.0.0.0', port=5000, debug=True)
